#!/usr/bin/env python

import subprocess
import sys

import hgtlib


def main(args):
    assert len(args) == 1
    group_id = args[0]
    before_id, after_id = hgtlib.get_before_and_after(".", group_id)
    print before_id, after_id
    subprocess.check_call(["git", "cl", "upload", "--branch=%s" % group_id,
                           before_id, after_id])


if __name__ == "__main__":
    main(sys.argv[1:])
